version: "3.5"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: develop
      POSTGRES_PASSWORD: postgres

  superhero:
    image: superhero-api:latest
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://172.17.0.1:5432/develop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
